name: social_media_carbon_footprint
description: "A research-focused mobile app that monitors social media usage and calculates its digital carbon footprint, featuring AI-powered Smart Tips to promote sustainable digital habits."
publish_to: 'none'
version: 2.0.0+2

environment:
  # Require Dart/Flutter 3.6.0 or later, but below 4.0.0
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # fl_chart library (for charts)
  fl_chart: ^0.66.1

  # SQLite local database
  sqflite: ^2.3.3
  path: ^1.9.0

  # CSV export
  path_provider: ^2.1.5
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

fonts:
  - family: Titillium
    fonts:
      - asset: assets/fonts/TitilliumWeb-Regular.ttf
      - asset: assets/fonts/TitilliumWeb-Bold.ttf
        weight: 700